/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cruzers
 */
 public class Cruz_LoginSystem extends javax.swing.JFrame {

    
    public static String username = "";

    
    
    /**
     * Creates new form Cruz_LoginSystem
     */
    public Cruz_LoginSystem() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username_Display = new javax.swing.JTextField();
        Password_Display = new javax.swing.JPasswordField();
        Login_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Signup_Button = new javax.swing.JLabel();
        CheckBox_ShowPass = new javax.swing.JCheckBox();
        user_logo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(59, 81, 183));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        Username_Display.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Username_Display.setForeground(new java.awt.Color(153, 153, 153));
        Username_Display.setText("enter username");
        Username_Display.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_DisplayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_DisplayFocusLost(evt);
            }
        });
        Username_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_DisplayActionPerformed(evt);
            }
        });
        jPanel1.add(Username_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 318, 43));

        Password_Display.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Password_Display.setForeground(new java.awt.Color(153, 153, 153));
        Password_Display.setText("enter password");
        Password_Display.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_DisplayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_DisplayFocusLost(evt);
            }
        });
        jPanel1.add(Password_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 318, 43));

        Login_Button.setBackground(new java.awt.Color(102, 153, 255));
        Login_Button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button.setText("LOGIN");
        Login_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        Login_Button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Login_ButtonKeyPressed(evt);
            }
        });
        jPanel1.add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 318, 43));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Don't have an account?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, -1, -1));

        Signup_Button.setFont(new java.awt.Font("Kartika", 1, 15)); // NOI18N
        Signup_Button.setForeground(new java.awt.Color(0, 0, 0));
        Signup_Button.setText("<html>\n<body>\n<u>Sign Up</u>\n</body>\n</html>");
        Signup_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Signup_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Signup_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Signup_ButtonMouseEntered(evt);
            }
        });
        jPanel1.add(Signup_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, 20));

        CheckBox_ShowPass.setForeground(new java.awt.Color(0, 0, 0));
        CheckBox_ShowPass.setText("Show password");
        CheckBox_ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_ShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBox_ShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

        user_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/contacts-24.png"))); // NOI18N
        jPanel1.add(user_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/lock.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 740));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/bg project.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 738));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 738));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
            // TODO add your handling code here:
        
        Connection conn = My_Connection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        
        String temp_password = String.valueOf(Password_Display.getPassword());
        
        if(Username_Display.getText().isEmpty() || temp_password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Fill Up All Fields");   
        } else{
            
             username = Username_Display.getText();
           
            try{
            ps=conn.prepareStatement("SELECT * FROM `user_data` WHERE `Username`=? AND `Password`=?");
            ps.setString(1, username);
            ps.setString(2, temp_password);
            
            rs = ps.executeQuery(); 
            
                if(rs.next()){
                JOptionPane.showMessageDialog(null, "Login Successful ");
                 this.dispose();
                 new login_successful().setVisible(true);
                }else{
                JOptionPane.showMessageDialog(null, "Username or Password are Incorrect ");
                }
            
                } catch (Exception ex){
                Logger.getLogger(Cruz_LoginSystem.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            
        }
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void CheckBox_ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_ShowPassActionPerformed
        char character_password = 0;
        if(CheckBox_ShowPass.isSelected()){
          Password_Display.setEchoChar(character_password);     
        }
        else {
            Password_Display.setEchoChar('*');
        }
        
    }//GEN-LAST:event_CheckBox_ShowPassActionPerformed

    private void Signup_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Signup_ButtonMouseClicked
        
        this.dispose();
        new Signup_Form().setVisible(true);
        
        
    }//GEN-LAST:event_Signup_ButtonMouseClicked

    private void Username_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_DisplayActionPerformed

    private void Signup_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Signup_ButtonMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_Signup_ButtonMouseEntered

    private void Login_ButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login_ButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_ButtonKeyPressed

    private void Username_DisplayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_DisplayFocusGained
        // TODO add your handling code here:
       // Username_Display.setText("");
       // Username_Display.setForeground(Color.black);
        
        String usernameValue = Username_Display.getText().trim().toLowerCase();
        
        if (usernameValue.equals("enter username")){
            Username_Display.setText("");
            Username_Display.setForeground(Color.black);
        }
        
        
    }//GEN-LAST:event_Username_DisplayFocusGained

    private void Password_DisplayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_DisplayFocusGained
        // TODO add your handling code here:
        //Password_Display.setText("");
        String passswordValue = Password_Display.getText().trim().toLowerCase();
        
        if (passswordValue.equals("enter password")){
            Password_Display.setText("");
            Password_Display.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_Password_DisplayFocusGained

    private void Username_DisplayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_DisplayFocusLost
        // TODO add your handling code here:
        
        String usernameValue = Username_Display.getText().trim().toLowerCase();
        
        if (usernameValue.equals("enter username") || usernameValue.equals("")){
            Username_Display.setText("enter username");
            Username_Display.setForeground(new Color(153,153,153));
        }
        
        
    }//GEN-LAST:event_Username_DisplayFocusLost

    private void Password_DisplayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_DisplayFocusLost
        // TODO add your handling code here:
        String passwordValue = Password_Display.getText().trim().toLowerCase();
        
        if (passwordValue.equals("enter password") || passwordValue.equals("")){
            Password_Display.setText("enter password");
            Password_Display.setForeground(new Color(153,153,153));
        }
       
    }//GEN-LAST:event_Password_DisplayFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cruz_LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cruz_LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cruz_LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cruz_LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cruz_LoginSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_ShowPass;
    private javax.swing.JButton Login_Button;
    private javax.swing.JPasswordField Password_Display;
    private javax.swing.JLabel Signup_Button;
    private javax.swing.JTextField Username_Display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel user_logo;
    // End of variables declaration//GEN-END:variables

    private Color Color(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
