/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;


/**
 *
 * @author cruzers
 */
public class login_successful extends javax.swing.JFrame {

    /**
     * Creates new form login_successful
     */
    public login_successful() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Welcome_panel = new javax.swing.JPanel();
        username_field = new javax.swing.JLabel();
        eltrigre_button = new javax.swing.JLabel();
        wolvesp2_button = new javax.swing.JLabel();
        lynx_button = new javax.swing.JLabel();
        sparrow_button = new javax.swing.JLabel();
        dragon_button = new javax.swing.JLabel();
        eagles_button = new javax.swing.JLabel();
        gorilla_button = new javax.swing.JLabel();
        foxx_button = new javax.swing.JLabel();
        wolvesp1_button = new javax.swing.JLabel();
        wolvesp2_button1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eagles = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eltigre = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sparrow = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dragon = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lynx = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        foxx = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        wolvesp1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        gorilla = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        wolvesp2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        eagles9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        raven = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome_panel.setBackground(new java.awt.Color(102, 204, 255));
        Welcome_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        Welcome_panel.setOpaque(false);
        Welcome_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_field.setFont(new java.awt.Font("Gadugi", 1, 45)); // NOI18N
        username_field.setForeground(new java.awt.Color(187, 245, 245));
        username_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username_field.setText("USERNAME");
        username_field.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Welcome_panel.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 520, 90));

        eltrigre_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        eltrigre_button.setForeground(new java.awt.Color(255, 255, 255));
        eltrigre_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eltrigre_button.setText("<html> <body> <u>EL TIGRE</u> </body> </html>");
        eltrigre_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eltrigre_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eltrigre_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(eltrigre_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 140, 80));

        wolvesp2_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        wolvesp2_button.setForeground(new java.awt.Color(255, 255, 255));
        wolvesp2_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wolvesp2_button.setText("<html>\n<body>\n<u>RAVEN</u>\n</body>\n</html>");
        wolvesp2_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wolvesp2_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wolvesp2_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(wolvesp2_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 110, 40));

        lynx_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lynx_button.setForeground(new java.awt.Color(255, 255, 255));
        lynx_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lynx_button.setText("<html>\n<body>\n<u>LYNX</u>\n</body>\n</html>");
        lynx_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lynx_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lynx_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(lynx_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 140, 80));

        sparrow_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        sparrow_button.setForeground(new java.awt.Color(255, 255, 255));
        sparrow_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sparrow_button.setText("<html>\n<body>\n<u>SPARROW</u>\n</body>\n</html>");
        sparrow_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sparrow_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sparrow_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(sparrow_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 140, 80));

        dragon_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        dragon_button.setForeground(new java.awt.Color(255, 255, 255));
        dragon_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dragon_button.setText("<html>\n<body>\n<u>DRAGON</u>\n</body>\n</html>");
        dragon_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dragon_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dragon_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(dragon_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 140, 80));

        eagles_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        eagles_button.setForeground(new java.awt.Color(255, 255, 255));
        eagles_button.setText("<html> <body> <u>EAGLES</u> </body> </html>");
        eagles_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eagles_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eagles_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(eagles_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 80, 40));

        gorilla_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        gorilla_button.setForeground(new java.awt.Color(255, 255, 255));
        gorilla_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gorilla_button.setText("<html>\n<body>\n<u>GORILLA</u>\n</body>\n</html>");
        gorilla_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gorilla_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gorilla_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(gorilla_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 100, 40));

        foxx_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        foxx_button.setForeground(new java.awt.Color(255, 255, 255));
        foxx_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foxx_button.setText("<html>\n<body>\n<u>FOXX</u>\n</body>\n</html>");
        foxx_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        foxx_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foxx_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(foxx_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 90, 40));

        wolvesp1_button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        wolvesp1_button.setForeground(new java.awt.Color(255, 255, 255));
        wolvesp1_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wolvesp1_button.setText("<html>\n<body>\n<u>WOLVES P1</u>\n</body>\n</html>");
        wolvesp1_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wolvesp1_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wolvesp1_buttonMouseClicked(evt);
            }
        });
        Welcome_panel.add(wolvesp1_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 110, 40));

        wolvesp2_button1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        wolvesp2_button1.setForeground(new java.awt.Color(255, 255, 255));
        wolvesp2_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wolvesp2_button1.setText("<html>\n<body>\n<u>WOLVES P2</u>\n</body>\n</html>");
        wolvesp2_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wolvesp2_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wolvesp2_button1MouseClicked(evt);
            }
        });
        Welcome_panel.add(wolvesp2_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, 110, 40));

        jLabel24.setFont(new java.awt.Font("Kartika", 1, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 204, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("<html>\n<body>\n<u>Log out</u>\n</body>\n</html>\n");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        Welcome_panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 70, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/Welcome Soldier!.png"))); // NOI18N
        Welcome_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(Welcome_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        eagles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 204, 255));
        jLabel3.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        eagles.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/eagles.png"))); // NOI18N
        eagles.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(eagles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        eltigre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 204, 255));
        jLabel4.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        eltigre.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/elTigre.png"))); // NOI18N
        eltigre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(eltigre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        sparrow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 255));
        jLabel6.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        sparrow.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/sparrow.png"))); // NOI18N
        sparrow.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(sparrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        dragon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 204, 255));
        jLabel8.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        dragon.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/dragonEye.png"))); // NOI18N
        dragon.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(dragon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        lynx.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 204, 255));
        jLabel10.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        lynx.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/lynx.png"))); // NOI18N
        lynx.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(lynx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        foxx.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 204, 255));
        jLabel12.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        foxx.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/foxx.png"))); // NOI18N
        foxx.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(foxx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        wolvesp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 204, 255));
        jLabel14.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        wolvesp1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/wolvesp1.png"))); // NOI18N
        wolvesp1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(wolvesp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        gorilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 204, 255));
        jLabel16.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        gorilla.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/gorilla.png"))); // NOI18N
        gorilla.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(gorilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        wolvesp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 204, 255));
        jLabel18.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        wolvesp2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/wolvesp2.png"))); // NOI18N
        wolvesp2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        eagles9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 204, 255));
        jLabel20.setText("Back");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        eagles9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/eagles.png"))); // NOI18N
        eagles9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        wolvesp2.add(eagles9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(wolvesp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        raven.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 204, 255));
        jLabel22.setText("<html>\n<body>\n<u>Back</u>\n</body>\n</html>");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        raven.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 60, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/raven.png"))); // NOI18N
        raven.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        getContentPane().add(raven, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        setUsername();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        eagles.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        eltigre.setVisible(false);
        Welcome_panel.setVisible(true);
       
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        sparrow.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        dragon.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        lynx.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        foxx.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        wolvesp1.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        gorilla.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        wolvesp2.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        raven.setVisible(false);
        Welcome_panel.setVisible(true);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void wolvesp2_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wolvesp2_buttonMouseClicked
        // TODO add your handling code here:
        raven.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_wolvesp2_buttonMouseClicked

    private void eltrigre_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eltrigre_buttonMouseClicked
        // TODO add your handling code here:
        eltigre.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_eltrigre_buttonMouseClicked

    private void lynx_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lynx_buttonMouseClicked
        // TODO add your handling code here:
        lynx.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_lynx_buttonMouseClicked

    private void sparrow_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparrow_buttonMouseClicked
        // TODO add your handling code here:
        sparrow.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_sparrow_buttonMouseClicked

    private void dragon_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragon_buttonMouseClicked
        // TODO add your handling code here:
        dragon.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_dragon_buttonMouseClicked

    private void eagles_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eagles_buttonMouseClicked
        // TODO add your handling code here:
        eagles.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_eagles_buttonMouseClicked

    private void foxx_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foxx_buttonMouseClicked
        // TODO add your handling code here:
        foxx.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_foxx_buttonMouseClicked

    private void gorilla_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gorilla_buttonMouseClicked
        // TODO add your handling code here:
        gorilla.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_gorilla_buttonMouseClicked

    private void wolvesp1_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wolvesp1_buttonMouseClicked
        // TODO add your handling code here:
        wolvesp1.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_wolvesp1_buttonMouseClicked

    private void wolvesp2_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wolvesp2_button1MouseClicked
        // TODO add your handling code here:
        wolvesp2.setVisible(true);
        Welcome_panel.setVisible(false);
    }//GEN-LAST:event_wolvesp2_button1MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Cruz_LoginSystem().setVisible(true);
    }//GEN-LAST:event_jLabel24MouseClicked
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_successful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_successful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_successful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_successful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_successful().setVisible(true);
            }
        });
        
        
       
       //  setUsername();
    }
    
    
    public  void setUsername(){
        
     String username =  Cruz_LoginSystem.username;
         username_field.setText(username);
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Welcome_panel;
    private javax.swing.JPanel dragon;
    private javax.swing.JLabel dragon_button;
    private javax.swing.JPanel eagles;
    private javax.swing.JPanel eagles9;
    private javax.swing.JLabel eagles_button;
    private javax.swing.JPanel eltigre;
    private javax.swing.JLabel eltrigre_button;
    private javax.swing.JPanel foxx;
    private javax.swing.JLabel foxx_button;
    private javax.swing.JPanel gorilla;
    private javax.swing.JLabel gorilla_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel lynx;
    private javax.swing.JLabel lynx_button;
    private javax.swing.JPanel raven;
    private javax.swing.JPanel sparrow;
    private javax.swing.JLabel sparrow_button;
    private javax.swing.JLabel username_field;
    private javax.swing.JPanel wolvesp1;
    private javax.swing.JLabel wolvesp1_button;
    private javax.swing.JPanel wolvesp2;
    private javax.swing.JLabel wolvesp2_button;
    private javax.swing.JLabel wolvesp2_button1;
    // End of variables declaration//GEN-END:variables
}
