/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.InputStream;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author cruzers
 */
public class Signup_Form extends javax.swing.JFrame {

    /**
     * Creates new form Signup_Form
     */
    String condition_image = null;
    
    public Signup_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Lastname_Display_Signup = new javax.swing.JTextField();
        Signup_Button = new javax.swing.JButton();
        Username_Display_Signup = new javax.swing.JTextField();
        Firstname_Display_Signup = new javax.swing.JTextField();
        Photo_Display_Signup = new javax.swing.JLabel();
        Browse_Button = new javax.swing.JButton();
        Password_Display_Signup = new javax.swing.JPasswordField();
        RetypePassword_Display_Signup = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        login_button_signup = new javax.swing.JLabel();
        haveAccount = new javax.swing.JLabel();
        Showpassword_bttn = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(185, 218, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Picture");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, 20));

        Lastname_Display_Signup.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        Lastname_Display_Signup.setForeground(new java.awt.Color(153, 153, 153));
        Lastname_Display_Signup.setText("enter lastname");
        Lastname_Display_Signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Lastname_Display_SignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lastname_Display_SignupFocusLost(evt);
            }
        });
        Lastname_Display_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lastname_Display_SignupActionPerformed(evt);
            }
        });
        jPanel1.add(Lastname_Display_Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 318, 40));

        Signup_Button.setBackground(new java.awt.Color(102, 153, 255));
        Signup_Button.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Signup_Button.setForeground(new java.awt.Color(255, 255, 255));
        Signup_Button.setText("Sign Up");
        Signup_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Signup_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Signup_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, 315, 40));

        Username_Display_Signup.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        Username_Display_Signup.setForeground(new java.awt.Color(153, 153, 153));
        Username_Display_Signup.setText("enter username");
        Username_Display_Signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_Display_SignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_Display_SignupFocusLost(evt);
            }
        });
        Username_Display_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_Display_SignupActionPerformed(evt);
            }
        });
        jPanel1.add(Username_Display_Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 318, 40));

        Firstname_Display_Signup.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        Firstname_Display_Signup.setForeground(new java.awt.Color(153, 153, 153));
        Firstname_Display_Signup.setText("enter firstname");
        Firstname_Display_Signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Firstname_Display_SignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Firstname_Display_SignupFocusLost(evt);
            }
        });
        Firstname_Display_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Firstname_Display_SignupActionPerformed(evt);
            }
        });
        jPanel1.add(Firstname_Display_Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 318, 40));

        Photo_Display_Signup.setBackground(new java.awt.Color(255, 255, 255));
        Photo_Display_Signup.setOpaque(true);
        jPanel1.add(Photo_Display_Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 315, 169));

        Browse_Button.setBackground(new java.awt.Color(204, 204, 204));
        Browse_Button.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        Browse_Button.setForeground(new java.awt.Color(51, 51, 51));
        Browse_Button.setText("Browse...");
        Browse_Button.setBorder(null);
        Browse_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Browse_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Browse_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 80, 30));

        Password_Display_Signup.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Password_Display_Signup.setForeground(new java.awt.Color(153, 153, 153));
        Password_Display_Signup.setText("enter password");
        Password_Display_Signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_Display_SignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_Display_SignupFocusLost(evt);
            }
        });
        Password_Display_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_Display_SignupActionPerformed(evt);
            }
        });
        jPanel1.add(Password_Display_Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 318, 40));

        RetypePassword_Display_Signup.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        RetypePassword_Display_Signup.setForeground(new java.awt.Color(153, 153, 153));
        RetypePassword_Display_Signup.setText("enter password");
        RetypePassword_Display_Signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RetypePassword_Display_SignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RetypePassword_Display_SignupFocusLost(evt);
            }
        });
        jPanel1.add(RetypePassword_Display_Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 318, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Firstname");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lastname");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Username");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Retype Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        login_button_signup.setBackground(new java.awt.Color(255, 255, 255));
        login_button_signup.setFont(new java.awt.Font("Kartika", 1, 17)); // NOI18N
        login_button_signup.setForeground(new java.awt.Color(19, 15, 15));
        login_button_signup.setText("<html> <body> <u>Log in</u> </body> </html>");
        login_button_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_button_signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_button_signupMouseEntered(evt);
            }
        });
        jPanel1.add(login_button_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 750, 80, 40));

        haveAccount.setBackground(new java.awt.Color(255, 255, 255));
        haveAccount.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        haveAccount.setForeground(new java.awt.Color(51, 51, 51));
        haveAccount.setText("Have an account?");
        haveAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        haveAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haveAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                haveAccountMouseEntered(evt);
            }
        });
        jPanel1.add(haveAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 760, -1, 20));

        Showpassword_bttn.setForeground(new java.awt.Color(12, 9, 9));
        Showpassword_bttn.setText("Show password");
        Showpassword_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Showpassword_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(Showpassword_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 800));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/Signup_Bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Signup_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_ButtonActionPerformed
        // TODO add your handling code here:
        
        String temp_password = String.valueOf(Password_Display_Signup.getPassword());
        String temp_retypepassword = String.valueOf(RetypePassword_Display_Signup.getPassword());
        
            if (Firstname_Display_Signup.getText().isEmpty() || Lastname_Display_Signup.getText().isEmpty()
                || Username_Display_Signup.getText().isEmpty() || temp_password.isEmpty()|| condition_image == null){
                JOptionPane.showMessageDialog(null, "Fill up All Fields"); 
               
            } else {
                if (!(temp_password.equals(temp_retypepassword))){
                 JOptionPane.showMessageDialog(null, "Password does not match");    
                }else{
                    
                   Connection conn = My_Connection.getConnection();
                   PreparedStatement ps;
                   
                    try {
                        ps = conn.prepareStatement("INSERT INTO `user_data`(`Firstname`, `Lastname`, `Username`, "
                                + "`Password`, `Picture`) VALUES (?,?,?,?,?)");
                        ps.setString(1, Firstname_Display_Signup.getText());
                        ps.setString(2, Lastname_Display_Signup.getText());
                        ps.setString(3, Username_Display_Signup.getText());
                        ps.setString(4, temp_password);
                        InputStream blob_img = new FileInputStream(new File(condition_image));
                        ps.setBlob(5, blob_img);
                        
                        if(ps.executeUpdate()==1){
                            JOptionPane.showMessageDialog(null,"Account Successfully Created"); 
                            this.dispose();
                            new Cruz_LoginSystem().setVisible(true);
                            
                        }else{
                           JOptionPane.showMessageDialog(null,"Account Creation Error"); 
                        }
                       
                        
                    } catch (Exception ex) {
                        Logger.getLogger(Signup_Form.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                    
                    
                }
            }   
    }//GEN-LAST:event_Signup_ButtonActionPerformed

 private void Username_Display_SignupActionPerformed(java.awt.event.ActionEvent evt){
    // TODO add your handling code here:
}   
  
    
    private void Lastname_Display_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lastname_Display_SignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lastname_Display_SignupActionPerformed

    private void Browse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse_ButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser browse = new JFileChooser();
        browse.setCurrentDirectory(new File (System.getProperty("user.home")));
        
        //File Extension
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("IMAGE FILES (*.jpg;*.jpeg;*.png;*.gif)",
                "jpg","png","gif");//File Extension
        
        browse.addChoosableFileFilter(fileFilter);  
        
       int fileImage = browse.showSaveDialog(null);
        
       if(fileImage == 0)
          {
            //JOptionPane.showMessageDialog(null,"Image Accepted"); 
            File selectedFile = browse.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            condition_image = path;
            ImageIcon myImage = new ImageIcon(path);
            Image scaled_img = myImage.getImage().getScaledInstance(Photo_Display_Signup.getWidth(),
                    Photo_Display_Signup.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon TrueImage = new ImageIcon(scaled_img);
            
            Photo_Display_Signup.setIcon(TrueImage);
           
          } 
       else
            {
           
                JOptionPane.showMessageDialog(null,"No Image Selected"); 
           
            }
        
       
        
    }//GEN-LAST:event_Browse_ButtonActionPerformed

        
    
    private void Firstname_Display_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Firstname_Display_SignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Firstname_Display_SignupActionPerformed

    private void login_button_signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_button_signupMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_button_signupMouseEntered

    private void login_button_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_button_signupMouseClicked

        this.dispose();
        new Cruz_LoginSystem().setVisible(true);
    }//GEN-LAST:event_login_button_signupMouseClicked

    private void haveAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_haveAccountMouseClicked

    private void haveAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccountMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_haveAccountMouseEntered

    private void Showpassword_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Showpassword_bttnActionPerformed
        // TODO add your handling code here:
        char character_password = 0;
        if(Showpassword_bttn.isSelected()){
          Password_Display_Signup.setEchoChar(character_password);     
        }
        else {
            Password_Display_Signup.setEchoChar('*');
        }
    
    }//GEN-LAST:event_Showpassword_bttnActionPerformed

    private void Lastname_Display_SignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lastname_Display_SignupFocusGained
        // TODO add your handling code here:
        String lastnameValue = Lastname_Display_Signup.getText().trim().toLowerCase();
        
        if (lastnameValue.equals("enter lastname")){
            Lastname_Display_Signup.setText("");
            Lastname_Display_Signup.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_Lastname_Display_SignupFocusGained

    private void Username_Display_SignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_Display_SignupFocusGained
        // TODO add your handling code here:
        String usernameValue = Username_Display_Signup.getText().trim().toLowerCase();
        
        if (usernameValue.equals("enter username")){
            Username_Display_Signup.setText("");
            Username_Display_Signup.setForeground(Color.black);
        }
    }//GEN-LAST:event_Username_Display_SignupFocusGained

    private void Password_Display_SignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_Display_SignupFocusGained
        // TODO add your handling code here:
        String passwordValue = Password_Display_Signup.getText().trim().toLowerCase();
        
        if (passwordValue.equals("enter password")){
            Password_Display_Signup.setText("");
            Password_Display_Signup.setForeground(Color.black);
        }
    }//GEN-LAST:event_Password_Display_SignupFocusGained

    private void RetypePassword_Display_SignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RetypePassword_Display_SignupFocusGained
        // TODO add your handling code here:
        String repasswordValue = RetypePassword_Display_Signup.getText().trim().toLowerCase();
        
        if (repasswordValue.equals("enter password")){
            RetypePassword_Display_Signup.setText("");
            RetypePassword_Display_Signup.setForeground(Color.black);
        }
    }//GEN-LAST:event_RetypePassword_Display_SignupFocusGained

    private void Firstname_Display_SignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Firstname_Display_SignupFocusGained
        // TODO add your handling code here:
        
        String firstnameValue = Firstname_Display_Signup.getText().trim().toLowerCase();
        
        if (firstnameValue.equals("enter firstname")){
            Firstname_Display_Signup.setText("");
            Firstname_Display_Signup.setForeground(Color.black);
        }
        
        
    }//GEN-LAST:event_Firstname_Display_SignupFocusGained

    private void Firstname_Display_SignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Firstname_Display_SignupFocusLost
        // TODO add your handling code here:
        String firstnameValue = Firstname_Display_Signup.getText().trim().toLowerCase();
        
        if (firstnameValue.equals("enter firstname") || firstnameValue.equals("")){
            Firstname_Display_Signup.setText("enter firstname");
            Firstname_Display_Signup.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_Firstname_Display_SignupFocusLost

    private void Lastname_Display_SignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lastname_Display_SignupFocusLost
        // TODO add your handling code here:
        String lastnameValue = Lastname_Display_Signup.getText().trim().toLowerCase();
        
        if (lastnameValue.equals("enter lasttname") || lastnameValue.equals("")){
            Lastname_Display_Signup.setText("enter lastname");
            Lastname_Display_Signup.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Lastname_Display_SignupFocusLost

    private void Username_Display_SignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_Display_SignupFocusLost
        // TODO add your handling code here:
        String usernameValue = Username_Display_Signup.getText().trim().toLowerCase();
        
        if (usernameValue.equals("enter username") || usernameValue.equals("")){
            Username_Display_Signup.setText("enter username");
            Username_Display_Signup.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Username_Display_SignupFocusLost

    private void Password_Display_SignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_Display_SignupFocusLost
        // TODO add your handling code here:
        String passwordValue = Password_Display_Signup.getText().trim().toLowerCase();
        
        if (passwordValue.equals("enter password") || passwordValue.equals("")){
            Password_Display_Signup.setText("enter password");
            Password_Display_Signup.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Password_Display_SignupFocusLost

    private void RetypePassword_Display_SignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RetypePassword_Display_SignupFocusLost
        // TODO add your handling code here:
        String repasswordValue = RetypePassword_Display_Signup.getText().trim().toLowerCase();
        
        if (repasswordValue.equals("enter password") || repasswordValue.equals("")){
            RetypePassword_Display_Signup.setText("enter password");
            RetypePassword_Display_Signup.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_RetypePassword_Display_SignupFocusLost

    private void Password_Display_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_Display_SignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_Display_SignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse_Button;
    private javax.swing.JTextField Firstname_Display_Signup;
    private javax.swing.JTextField Lastname_Display_Signup;
    private javax.swing.JPasswordField Password_Display_Signup;
    private javax.swing.JLabel Photo_Display_Signup;
    private javax.swing.JPasswordField RetypePassword_Display_Signup;
    private javax.swing.JCheckBox Showpassword_bttn;
    private javax.swing.JButton Signup_Button;
    private javax.swing.JTextField Username_Display_Signup;
    private javax.swing.JLabel haveAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login_button_signup;
    // End of variables declaration//GEN-END:variables
}
